/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.dextop.api.Models;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        System.out.println(Models.stringToE8("0.00003266"));
    }
}
